# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/configuration/ and in linters documentation

---
PRE_COMMANDS:
  - command: pip install pipenv
    cwd: "workspace"
  - command: PIPENV_VENV_IN_PROJECT=1 pipenv install
    cwd: "workspace"

APPLY_FIXES: all
DISABLE:
  - COPYPASTE
  - DOCKERFILE
  - REPOSITORY
  - SPELL
DISABLE_LINTERS:
  - MAKEFILE_CHECKMAKE
  - PYTHON_PYLINT
PLUGINS:
  - https://raw.githubusercontent.com/cdzombak/mega-linter-plugin-dockerfilelint/main/mega-linter-plugin-dockerfilelint/dockerfilelint.megalinter-descriptor.yml

MARKDOWN_MARKDOWNLINT_ARGUMENTS: "--disable MD013"
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: '(\.devcontainer\/devcontainer\.json|\.vscode\/launch\.json)'
PYTHON_FILTER_REGEX_EXCLUDE: '(\.venv|test_.*\.py)'
ACTION_ACTIONLINT_ARGUMENTS: '-shellcheck=""'

VALIDATE_ALL_CODEBASE: true
SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false
PRINT_ALPACA: false
